// Build-time helper. Reads the Inter TTF files in this script's directory
// (drop them in before running) and emits base64-encoded TS modules under
// src/lib/pdf-fonts/. Run once when the embedded font changes:
//
//   node scripts/encode-fonts.mjs <regular-ttf-path> <bold-ttf-path>
//
// The generated .ts files are committed alongside the TTFs (which can then
// be deleted from the working tree — they live in git history via the
// generated base64 string and the LICENSE file).

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'src/lib/pdf-fonts');

const args = process.argv.slice(2);
if (args.length !== 2) {
  console.error('Usage: node scripts/encode-fonts.mjs <regular.ttf> <bold.ttf>');
  process.exit(1);
}

const [regularPath, boldPath] = args;

function encode(name, ttfPath, exportName, outFile) {
  const buf = fs.readFileSync(ttfPath);
  const b64 = buf.toString('base64');
  const ts = `// AUTO-GENERATED by scripts/encode-fonts.mjs — do not edit by hand.
// Source: Inter ${name}, SIL Open Font License 1.1 (see LICENSE-Inter.txt).
// Original TTF size: ${buf.length} bytes.

export const ${exportName} = '${b64}';
`;
  fs.writeFileSync(outFile, ts);
  console.log(`wrote ${path.relative(ROOT, outFile)}  (${buf.length} B raw → ${b64.length} B base64)`);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
encode('Regular',  regularPath, 'INTER_REGULAR_BASE64', path.join(OUT_DIR, 'inter-regular.ts'));
encode('Bold',     boldPath,    'INTER_BOLD_BASE64',    path.join(OUT_DIR, 'inter-bold.ts'));
